### ISSUE TITLE
Add log-format option 

### ISSUE THREAD

**Issue by alexseys** [propyless/puppet-module-haproxywrapper#9]
Hi,
Thank you for help with previous issue, i still have to learn them tables.
Trying to add log-format option as such:
```
  https_in:
    bind:
      '0.0.0.0:443': 'ssl crt /etc/ssl/private/haproxy/' 
    mode: 'http'
    options:
      http-request: 'track-sc1 src table st_src_global'
      http-request: 'deny deny_status 429 if { sc_http_req_rate(0) gt 100 }'
      option:
        - 'http-server-close'
        - 'log-format "%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r"'
      use_backend:
```
.............
And getting this error:
```
Info: Computing checksum on file /etc/haproxy/haproxy.cfg
Info: /Stage[main]/Haproxy/Haproxy::Instance[haproxy]/Haproxy::Config[haproxy]/Concat[/etc/haproxy/haproxy.cfg]/File[/etc/haproxy/haproxy.cfg]: Filebucketed /etc/haproxy/haproxy.cfg to puppet with sum 12b2408b5e017d504ce7207b02d83386
Error: Execution of '/usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg20200306-94378-17kbqy3 -c' returned 1: [ALERT] 065/094045 (94968) : parsing [/etc/haproxy/haproxy.cfg20200306-94378-17kbqy3:41] : ### unknown option 'log-format'.
[ALERT] 065/094045 (94968) : parsing [/etc/haproxy/haproxy.cfg20200306-94378-17kbqy3:62] : unknown option 'log-format'.
[ALERT] 065/094045 (94968) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg20200306-94378-17kbqy3
[ALERT] 065/094045 (94968) : Fatal errors found in configuration.
```
How would I add log-format?

Adding same line manually works just fine:
```
frontend https_in
  bind 0.0.0.0:443 ssl crt /etc/ssl/private/haproxy/
  mode http
  http-request deny deny_status 429 if { sc_http_req_rate(0) gt 100 }
  option http-server-close
 #option httplog
  log-format "%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r"
```
Also if I replace log-format with httplog that works fine
Also is there a way to print out config file  to be addied during puppet run?

**Comment by anders-larsson** [comment]
Hi,

First of all. Sorry I didn't get a notification regarding this issue so it was completely missed. I cannot directly say what's going wrong but it appears log-format is added to the wrong location of the haproxy.cfg file. I think it should be _outside_ of the option: section because I suspect it becomes 
`option log-format "%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r"` which according to the output is incorrect. It should be
`log-format "%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r"`.

What happens if you configure it as below? I'm just guessing though.
```
  https_in:
    bind:
      '0.0.0.0:443': 'ssl crt /etc/ssl/private/haproxy/' 
    mode: 'http'
    options:
      http-request: 'track-sc1 src table st_src_global'
      http-request: 'deny deny_status 429 if { sc_http_req_rate(0) gt 100 }'
      log-format: '%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r'
      option:
        - 'http-server-close'
      use_backend:
```

**Comment by alexseys** [comment]
No problem at all
Thank you for replying
I’ll try this over next couple of days and let you know

**Comment by alexseys** [comment]
solution above works 

options:
      http-request: 'track-sc1 src table st_src_global'
      http-request: 'deny deny_status 429 if { sc_http_req_rate(0) gt 100 }'
      log-format: '%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r'
    Thank You

Just an update for anyone who might care, this works with haproxy v2.17:

  https_in:
    bind:
      '0.0.0.0:443': 'ssl crt /etc/ssl/private/haproxy/'
    mode: 'http'
    options:
      log-format: '"%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r"'
      http-request:
        - 'add-header X-Forwarded-Proto https'
        - 'track-sc0 src table st_src_global '
        - 'deny deny_status 429 if { sc_http_req_rate(0) gt 1000 }'
